### ISSUE TITLE
test_udp_source.py doesn't compile

### ISSUE THREAD

**Issue by BCITMike** [ghostop14/gr-grnet#4]
test_udp_source.py doesn't compile.  When I disabled two of the three inputs to the throttle, then it would compile the flowgraph.  Seemed strange to have UDP source, TCP source and a waveform generator all connected to the throttle block.
A test for loopback between source and sink would be ideal.

**Comment by ghostop14** [comment]
The 2 disabled blocks were there for testing.  Any one of the 3 could be enabled with the other two disabled.  I removed the disabled inputs to avoid confusion.
