### ISSUE TITLE
GRNET tcp sink tcp source udp sink udp source error 

### ISSUE THREAD

**Issue by saogo** [ghostop14/gr-grnet#8]
![captura de pantalla de 2018-03-03 12-58-07](https://user-images.githubusercontent.com/36648154/36937507-8e722486-1ee2-11e8-8c50-e2f751c107ab.png)
good morning I'm starting to know GNURADIO for a project I have in the university and I found this post that can help me, when trying to install gr-grnet packages it seems that everything works perfect but when I go to review the examples there are some lost blocks so that the examples are correct, the blocks are GRNET tcp and udp sink source but I do not know what I can do to be used correctly, if any of you could help me I would appreciate it immensely.

Thank you

**Comment by ghostop14** [comment]
Looks like the block definition files didn't install into the gnuradio path.  When you did "make install" did you get any errors?  Sometimes depending on how you have gnuradio installed you may need to "sudo make install" instead, for instance if you installed from the apt repos versus pybombs.

**Comment by saogo** [comment]
Hi ghostop14 thank you for responding so quickly, and for your help, thank you very much for everything

**Comment by ghostop14** [comment]
You're welcome!
